import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import I18nProvider from "../providers/I18nProvider";
import { Navigation } from "../components/Menu/Menu";
import Footer from "./main/footer";
import Header from "./main/header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "SACS Aerospace Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<I18nProvider>
					<Header />
					<Navigation />
					{children}
					<Footer />
				</I18nProvider>
			</body>
		</html>
	);
}
